"""Add warehouse and customer entities

Revision ID: 3b0c1aba96de
Revises: 
Create Date: 2026-02-07 19:39:06.513661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b0c1aba96de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_type',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_address_type_name'), 'address_type', ['name'], unique=True)
    op.create_table('audit_log',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=250), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.String(length=150), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('ix_audit_category', 'audit_log', ['category'], unique=False)
    op.create_index('ix_audit_entity_id', 'audit_log', ['entity_id'], unique=False)
    op.create_index('ix_audit_entity_type', 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_category'), 'audit_log', ['category'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('country',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('phone_pre', sa.String(length=10), nullable=True),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_country_country_code'), 'country', ['country_code'], unique=True)
    op.create_index(op.f('ix_country_name'), 'country', ['name'], unique=False)
    op.create_table('customer',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('partner_type', sa.Enum('INDIVIDUAL', 'CORPORATION', 'GOVERNMENT', 'NON_PROFIT', name='partner_type'), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('credit_limit', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index('ix_customer_active', 'customer', ['is_active'], unique=False)
    op.create_index(op.f('ix_customer_code'), 'customer', ['code'], unique=True)
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=False)
    op.create_table('delivery_condition',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_delivery_condition_name'), 'delivery_condition', ['name'], unique=False)
    op.create_table('payment_term',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('days_due', sa.String(length=20), nullable=True),
    sa.Column('discount_percent', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_payment_term_name'), 'payment_term', ['name'], unique=False)
    op.create_table('price_list',
    sa.Column('price_list_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('price_list_id')
    )
    op.create_index('ix_price_list_active', 'price_list', ['is_active'], unique=False)
    op.create_index(op.f('ix_price_list_name'), 'price_list', ['name'], unique=True)
    op.create_table('product_category',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_category_id'], ['product_category.category_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_category_parent', 'product_category', ['parent_category_id'], unique=False)
    op.create_index(op.f('ix_product_category_name'), 'product_category', ['name'], unique=False)
    op.create_table('supplier',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('partner_type', sa.Enum('INDIVIDUAL', 'CORPORATION', 'GOVERNMENT', 'NON_PROFIT', name='partner_type'), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_index('ix_supplier_active', 'supplier', ['is_active'], unique=False)
    op.create_index(op.f('ix_supplier_code'), 'supplier', ['code'], unique=True)
    op.create_index(op.f('ix_supplier_name'), 'supplier', ['name'], unique=False)
    op.create_table('unit_of_measure',
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_base_unit', sa.Boolean(), nullable=False),
    sa.Column('conversion_factor', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_index(op.f('ix_unit_of_measure_code'), 'unit_of_measure', ['code'], unique=True)
    op.create_index('ix_uom_category', 'unit_of_measure', ['category'], unique=False)
    op.create_table('warehouse',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('manager', sa.String(length=150), nullable=True),
    sa.Column('capacity_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('warehouse_id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_warehouse_active', 'warehouse', ['is_active'], unique=False)
    op.create_index(op.f('ix_warehouse_name'), 'warehouse', ['name'], unique=True)
    op.create_table('legal_form',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_uuid'], ['country.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('ix_legal_form_country', 'legal_form', ['country_uuid'], unique=False)
    op.create_index(op.f('ix_legal_form_name'), 'legal_form', ['name'], unique=False)
    op.create_table('product',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('base_uom_id', sa.UUID(), nullable=False),
    sa.Column('track_by_lot', sa.Boolean(), nullable=False),
    sa.Column('track_by_serial', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['base_uom_id'], ['unit_of_measure.unit_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.category_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index('ix_product_active', 'product', ['is_active'], unique=False)
    op.create_index('ix_product_category', 'product', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_sku'), 'product', ['sku'], unique=True)
    op.create_table('purchase_order',
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED', name='order_status_purchase'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.supplier_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.warehouse_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('po_id')
    )
    op.create_index('ix_po_status', 'purchase_order', ['status'], unique=False)
    op.create_index('ix_po_supplier', 'purchase_order', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_po_number'), 'purchase_order', ['po_number'], unique=True)
    op.create_table('sales_order',
    sa.Column('so_id', sa.UUID(), nullable=False),
    sa.Column('so_number', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'PARTIALLY_FULFILLED', 'FULFILLED', 'CANCELLED', name='order_status_sales'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.warehouse_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('so_id')
    )
    op.create_index(op.f('ix_sales_order_so_number'), 'sales_order', ['so_number'], unique=True)
    op.create_index('ix_so_customer', 'sales_order', ['customer_id'], unique=False)
    op.create_index('ix_so_status', 'sales_order', ['status'], unique=False)
    op.create_table('stock_document',
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('doc_number', sa.String(length=100), nullable=False),
    sa.Column('doc_type', sa.Enum('RECEIVING', 'SHIPPING', 'TRANSFER', 'ADJUSTMENT', 'MANUFACTURING_CONSUMPTION', 'MANUFACTURING_OUTPUT', name='doc_type'), nullable=False),
    sa.Column('doc_status', sa.Enum('DRAFT', 'POSTED', 'CANCELLED', name='doc_status'), nullable=False),
    sa.Column('source_warehouse_id', sa.UUID(), nullable=True),
    sa.Column('dest_warehouse_id', sa.UUID(), nullable=True),
    sa.Column('doc_date', sa.Date(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dest_warehouse_id'], ['warehouse.warehouse_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['warehouse.warehouse_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index('ix_stock_doc_source', 'stock_document', ['source_warehouse_id'], unique=False)
    op.create_index('ix_stock_doc_status', 'stock_document', ['doc_status'], unique=False)
    op.create_index('ix_stock_doc_type', 'stock_document', ['doc_type'], unique=False)
    op.create_index(op.f('ix_stock_document_doc_number'), 'stock_document', ['doc_number'], unique=True)
    op.create_table('stocktake',
    sa.Column('stocktake_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('count_date', sa.Date(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('supervisor', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.warehouse_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('stocktake_id')
    )
    op.create_index('ix_stocktake_finalized', 'stocktake', ['is_finalized'], unique=False)
    op.create_index(op.f('ix_stocktake_reference'), 'stocktake', ['reference'], unique=True)
    op.create_index('ix_stocktake_warehouse', 'stocktake', ['warehouse_id'], unique=False)
    op.create_table('storage_location',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location_type', sa.Enum('STANDARD_RACK', 'HIGH_SHELF', 'FLOOR_SPACE', 'COLD_STORAGE', 'QUARANTINE_ZONE', 'RECEIVING_DOCK', 'SHIPPING_DOCK', name='location_type'), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.warehouse_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index('ix_location_available', 'storage_location', ['is_available'], unique=False)
    op.create_index('ix_location_composite', 'storage_location', ['warehouse_id', 'code'], unique=True)
    op.create_index('ix_location_warehouse', 'storage_location', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_storage_location_code'), 'storage_location', ['code'], unique=False)
    op.create_table('customer_entity',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email_address', sa.String(length=200), nullable=True),
    sa.Column('firm_name', sa.String(length=250), nullable=True),
    sa.Column('vat_id', sa.String(length=50), nullable=True),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('tax_country_uuid', sa.UUID(), nullable=True),
    sa.Column('legal_form_uuid', sa.UUID(), nullable=True),
    sa.Column('payment_term_uuid', sa.UUID(), nullable=True),
    sa.Column('delivery_condition_uuid', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_condition_uuid'], ['delivery_condition.uuid'], ),
    sa.ForeignKeyConstraint(['legal_form_uuid'], ['legal_form.uuid'], ),
    sa.ForeignKeyConstraint(['payment_term_uuid'], ['payment_term.uuid'], ),
    sa.ForeignKeyConstraint(['tax_country_uuid'], ['country.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('ix_customer_entity_active', 'customer_entity', ['is_active'], unique=False)
    op.create_index('ix_customer_entity_legal_form', 'customer_entity', ['legal_form_uuid'], unique=False)
    op.create_index(op.f('ix_customer_entity_name'), 'customer_entity', ['name'], unique=False)
    op.create_index('ix_customer_entity_tax_country', 'customer_entity', ['tax_country_uuid'], unique=False)
    op.create_table('product_variant',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('attributes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variant_id')
    )
    op.create_index(op.f('ix_product_variant_sku'), 'product_variant', ['sku'], unique=True)
    op.create_index('ix_variant_active', 'product_variant', ['is_active'], unique=False)
    op.create_index('ix_variant_product', 'product_variant', ['product_id'], unique=False)
    op.create_table('address',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=False),
    sa.Column('house_number', sa.String(length=20), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=False),
    sa.Column('country_uuid', sa.UUID(), nullable=False),
    sa.Column('customer_uuid', sa.UUID(), nullable=True),
    sa.Column('type_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_uuid'], ['country.uuid'], ),
    sa.ForeignKeyConstraint(['customer_uuid'], ['customer_entity.uuid'], ),
    sa.ForeignKeyConstraint(['type_uuid'], ['address_type.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('ix_address_country', 'address', ['country_uuid'], unique=False)
    op.create_index('ix_address_customer', 'address', ['customer_uuid'], unique=False)
    op.create_index('ix_address_type', 'address', ['type_uuid'], unique=False)
    op.create_table('change_history',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('customer_uuid', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=200), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_uuid'], ['customer_entity.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('ix_change_history_customer', 'change_history', ['customer_uuid'], unique=False)
    op.create_index('ix_change_history_date', 'change_history', ['changed_at'], unique=False)
    op.create_table('contact_person',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('customer_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_uuid'], ['customer_entity.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('ix_contact_person_customer', 'contact_person', ['customer_uuid'], unique=False)
    op.create_table('inventory_reservation',
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FULFILLED', 'EXPIRED', 'CANCELLED', name='reservation_status'), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['storage_location.location_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.variant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.warehouse_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    op.create_index('ix_reservation_product', 'inventory_reservation', ['product_id'], unique=False)
    op.create_index('ix_reservation_status', 'inventory_reservation', ['status'], unique=False)
    op.create_index('ix_reservation_warehouse', 'inventory_reservation', ['warehouse_id'], unique=False)
    op.create_table('lot',
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('manufactured_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.supplier_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.variant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lot_id')
    )
    op.create_index('ix_lot_expiry', 'lot', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_lot_lot_number'), 'lot', ['lot_number'], unique=False)
    op.create_index('ix_lot_product', 'lot', ['product_id'], unique=False)
    op.create_index('ix_lot_variant', 'lot', ['variant_id'], unique=False)
    op.create_table('price_rule',
    sa.Column('price_rule_id', sa.UUID(), nullable=False),
    sa.Column('price_list_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('min_quantity', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_list.price_list_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.variant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('price_rule_id')
    )
    op.create_index('ix_price_rule_list', 'price_rule', ['price_list_id'], unique=False)
    op.create_index('ix_price_rule_product', 'price_rule', ['product_id'], unique=False)
    op.create_index('ix_price_rule_variant', 'price_rule', ['variant_id'], unique=False)
    op.create_table('purchase_order_line',
    sa.Column('po_line_id', sa.UUID(), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.String(length=10), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity_ordered', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.po_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.variant_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('po_line_id')
    )
    op.create_index('ix_po_line_po', 'purchase_order_line', ['po_id'], unique=False)
    op.create_table('sales_order_line',
    sa.Column('so_line_id', sa.UUID(), nullable=False),
    sa.Column('so_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.String(length=10), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity_ordered', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('quantity_fulfilled', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['so_id'], ['sales_order.so_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.variant_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('so_line_id')
    )
    op.create_index('ix_so_line_so', 'sales_order_line', ['so_id'], unique=False)
    op.create_table('inventory_balance',
    sa.Column('balance_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('lot_id', sa.UUID(), nullable=True),
    sa.Column('quantity_on_hand', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('quantity_reserved', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('quantity_available', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity_on_hand >= 0', name='chk_qoh_positive'),
    sa.CheckConstraint('quantity_reserved >= 0', name='chk_reserved_positive'),
    sa.ForeignKeyConstraint(['location_id'], ['storage_location.location_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.lot_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.variant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.warehouse_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('balance_id')
    )
    op.create_index('ix_balance_composite', 'inventory_balance', ['product_id', 'variant_id', 'warehouse_id', 'location_id', 'lot_id'], unique=False)
    op.create_index('ix_balance_location', 'inventory_balance', ['location_id'], unique=False)
    op.create_index('ix_balance_product', 'inventory_balance', ['product_id'], unique=False)
    op.create_index('ix_balance_variant', 'inventory_balance', ['variant_id'], unique=False)
    op.create_index('ix_balance_warehouse', 'inventory_balance', ['warehouse_id'], unique=False)
    op.create_table('serial_number',
    sa.Column('serial_id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('lot_id', sa.UUID(), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('IN_STOCK', 'RESERVED', 'SOLD', 'DEFECTIVE', name='serial_status'), nullable=False),
    sa.Column('warranty_expiry', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['storage_location.location_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.lot_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.variant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.warehouse_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('serial_id')
    )
    op.create_index(op.f('ix_serial_number_serial_number'), 'serial_number', ['serial_number'], unique=True)
    op.create_index('ix_serial_product', 'serial_number', ['product_id'], unique=False)
    op.create_index('ix_serial_status', 'serial_number', ['status'], unique=False)
    op.create_index('ix_serial_warehouse', 'serial_number', ['warehouse_id'], unique=False)
    op.create_table('stock_document_line',
    sa.Column('line_id', sa.UUID(), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.String(length=10), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('lot_id', sa.UUID(), nullable=True),
    sa.Column('source_location_id', sa.UUID(), nullable=True),
    sa.Column('dest_location_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('uom_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dest_location_id'], ['storage_location.location_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doc_id'], ['stock_document.doc_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.lot_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_location_id'], ['storage_location.location_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uom_id'], ['unit_of_measure.unit_id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.variant_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('line_id')
    )
    op.create_index('ix_stock_line_doc', 'stock_document_line', ['doc_id'], unique=False)
    op.create_table('stocktake_line',
    sa.Column('line_id', sa.UUID(), nullable=False),
    sa.Column('stocktake_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('lot_id', sa.UUID(), nullable=True),
    sa.Column('system_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('counted_quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('variance', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('counter', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['storage_location.location_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.lot_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stocktake_id'], ['stocktake.stocktake_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.variant_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('line_id')
    )
    op.create_index('ix_stocktake_line_stocktake', 'stocktake_line', ['stocktake_id'], unique=False)
    op.create_table('stock_movement',
    sa.Column('movement_id', sa.UUID(), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=True),
    sa.Column('line_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('lot_id', sa.UUID(), nullable=True),
    sa.Column('source_warehouse_id', sa.UUID(), nullable=True),
    sa.Column('source_location_id', sa.UUID(), nullable=True),
    sa.Column('dest_warehouse_id', sa.UUID(), nullable=True),
    sa.Column('dest_location_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('movement_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dest_location_id'], ['storage_location.location_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dest_warehouse_id'], ['warehouse.warehouse_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doc_id'], ['stock_document.doc_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['line_id'], ['stock_document_line.line_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['lot.lot_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_location_id'], ['storage_location.location_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['warehouse.warehouse_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.variant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movement_id')
    )
    op.create_index('ix_movement_dest_wh', 'stock_movement', ['dest_warehouse_id'], unique=False)
    op.create_index('ix_movement_doc', 'stock_movement', ['doc_id'], unique=False)
    op.create_index('ix_movement_product', 'stock_movement', ['product_id'], unique=False)
    op.create_index('ix_movement_source_wh', 'stock_movement', ['source_warehouse_id'], unique=False)
    op.create_index('ix_movement_timestamp', 'stock_movement', ['movement_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movement_timestamp', table_name='stock_movement')
    op.drop_index('ix_movement_source_wh', table_name='stock_movement')
    op.drop_index('ix_movement_product', table_name='stock_movement')
    op.drop_index('ix_movement_doc', table_name='stock_movement')
    op.drop_index('ix_movement_dest_wh', table_name='stock_movement')
    op.drop_table('stock_movement')
    op.drop_index('ix_stocktake_line_stocktake', table_name='stocktake_line')
    op.drop_table('stocktake_line')
    op.drop_index('ix_stock_line_doc', table_name='stock_document_line')
    op.drop_table('stock_document_line')
    op.drop_index('ix_serial_warehouse', table_name='serial_number')
    op.drop_index('ix_serial_status', table_name='serial_number')
    op.drop_index('ix_serial_product', table_name='serial_number')
    op.drop_index(op.f('ix_serial_number_serial_number'), table_name='serial_number')
    op.drop_table('serial_number')
    op.drop_index('ix_balance_warehouse', table_name='inventory_balance')
    op.drop_index('ix_balance_variant', table_name='inventory_balance')
    op.drop_index('ix_balance_product', table_name='inventory_balance')
    op.drop_index('ix_balance_location', table_name='inventory_balance')
    op.drop_index('ix_balance_composite', table_name='inventory_balance')
    op.drop_table('inventory_balance')
    op.drop_index('ix_so_line_so', table_name='sales_order_line')
    op.drop_table('sales_order_line')
    op.drop_index('ix_po_line_po', table_name='purchase_order_line')
    op.drop_table('purchase_order_line')
    op.drop_index('ix_price_rule_variant', table_name='price_rule')
    op.drop_index('ix_price_rule_product', table_name='price_rule')
    op.drop_index('ix_price_rule_list', table_name='price_rule')
    op.drop_table('price_rule')
    op.drop_index('ix_lot_variant', table_name='lot')
    op.drop_index('ix_lot_product', table_name='lot')
    op.drop_index(op.f('ix_lot_lot_number'), table_name='lot')
    op.drop_index('ix_lot_expiry', table_name='lot')
    op.drop_table('lot')
    op.drop_index('ix_reservation_warehouse', table_name='inventory_reservation')
    op.drop_index('ix_reservation_status', table_name='inventory_reservation')
    op.drop_index('ix_reservation_product', table_name='inventory_reservation')
    op.drop_table('inventory_reservation')
    op.drop_index('ix_contact_person_customer', table_name='contact_person')
    op.drop_table('contact_person')
    op.drop_index('ix_change_history_date', table_name='change_history')
    op.drop_index('ix_change_history_customer', table_name='change_history')
    op.drop_table('change_history')
    op.drop_index('ix_address_type', table_name='address')
    op.drop_index('ix_address_customer', table_name='address')
    op.drop_index('ix_address_country', table_name='address')
    op.drop_table('address')
    op.drop_index('ix_variant_product', table_name='product_variant')
    op.drop_index('ix_variant_active', table_name='product_variant')
    op.drop_index(op.f('ix_product_variant_sku'), table_name='product_variant')
    op.drop_table('product_variant')
    op.drop_index('ix_customer_entity_tax_country', table_name='customer_entity')
    op.drop_index(op.f('ix_customer_entity_name'), table_name='customer_entity')
    op.drop_index('ix_customer_entity_legal_form', table_name='customer_entity')
    op.drop_index('ix_customer_entity_active', table_name='customer_entity')
    op.drop_table('customer_entity')
    op.drop_index(op.f('ix_storage_location_code'), table_name='storage_location')
    op.drop_index('ix_location_warehouse', table_name='storage_location')
    op.drop_index('ix_location_composite', table_name='storage_location')
    op.drop_index('ix_location_available', table_name='storage_location')
    op.drop_table('storage_location')
    op.drop_index('ix_stocktake_warehouse', table_name='stocktake')
    op.drop_index(op.f('ix_stocktake_reference'), table_name='stocktake')
    op.drop_index('ix_stocktake_finalized', table_name='stocktake')
    op.drop_table('stocktake')
    op.drop_index(op.f('ix_stock_document_doc_number'), table_name='stock_document')
    op.drop_index('ix_stock_doc_type', table_name='stock_document')
    op.drop_index('ix_stock_doc_status', table_name='stock_document')
    op.drop_index('ix_stock_doc_source', table_name='stock_document')
    op.drop_table('stock_document')
    op.drop_index('ix_so_status', table_name='sales_order')
    op.drop_index('ix_so_customer', table_name='sales_order')
    op.drop_index(op.f('ix_sales_order_so_number'), table_name='sales_order')
    op.drop_table('sales_order')
    op.drop_index(op.f('ix_purchase_order_po_number'), table_name='purchase_order')
    op.drop_index('ix_po_supplier', table_name='purchase_order')
    op.drop_index('ix_po_status', table_name='purchase_order')
    op.drop_table('purchase_order')
    op.drop_index(op.f('ix_product_sku'), table_name='product')
    op.drop_index('ix_product_category', table_name='product')
    op.drop_index('ix_product_active', table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_legal_form_name'), table_name='legal_form')
    op.drop_index('ix_legal_form_country', table_name='legal_form')
    op.drop_table('legal_form')
    op.drop_index(op.f('ix_warehouse_name'), table_name='warehouse')
    op.drop_index('ix_warehouse_active', table_name='warehouse')
    op.drop_table('warehouse')
    op.drop_index('ix_uom_category', table_name='unit_of_measure')
    op.drop_index(op.f('ix_unit_of_measure_code'), table_name='unit_of_measure')
    op.drop_table('unit_of_measure')
    op.drop_index(op.f('ix_supplier_name'), table_name='supplier')
    op.drop_index(op.f('ix_supplier_code'), table_name='supplier')
    op.drop_index('ix_supplier_active', table_name='supplier')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_product_category_name'), table_name='product_category')
    op.drop_index('ix_category_parent', table_name='product_category')
    op.drop_table('product_category')
    op.drop_index(op.f('ix_price_list_name'), table_name='price_list')
    op.drop_index('ix_price_list_active', table_name='price_list')
    op.drop_table('price_list')
    op.drop_index(op.f('ix_payment_term_name'), table_name='payment_term')
    op.drop_table('payment_term')
    op.drop_index(op.f('ix_delivery_condition_name'), table_name='delivery_condition')
    op.drop_table('delivery_condition')
    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_code'), table_name='customer')
    op.drop_index('ix_customer_active', table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_country_name'), table_name='country')
    op.drop_index(op.f('ix_country_country_code'), table_name='country')
    op.drop_table('country')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_category'), table_name='audit_log')
    op.drop_index('ix_audit_entity_type', table_name='audit_log')
    op.drop_index('ix_audit_entity_id', table_name='audit_log')
    op.drop_index('ix_audit_category', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_address_type_name'), table_name='address_type')
    op.drop_table('address_type')
    # ### end Alembic commands ###
